# 以下配置兼容环境变量设置,配置文件优先级高于环境变量
# PROXY: "" # 代理地址 默认值 "",支持http https socks5
REFRESHCOOKIE: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..-JsC09lyWElXvkwX.1VCWEDCPW4mG8LjzdCDXqk8pyIOwYBjGwycxOWdU85nFSwWgehRJHh6sZKTLLzJ4TFdzBOQyiuHgR0WxslQyTV6NGWxSwoYvt6_2FC5Cixw2Yv-wNF3Bi3AvG1t7C1vgGI9mjf6gO7tLT4MZ3jPt6r0YAgXRbhVYIf8A0rtW91Wq_DAH07uYpKRD8yCeVSX7Q5iOIikUNcCbY8N5HXaX0a9cgHO9tqXm6ACtBScPMoTgQxmOfHvjaa7-noCFAcG1IlmBjq_WWoivagcAR2cEIg4DdPWdC7bbsJ3wM5_W6FTEdsJRIudiveO4BVAEVCV8zz_aJcR-T6lL_hb7GNlHUE27lLmZEWC2HGN9TxwjpZH8kxtjFh9PgtZaucLsnN2HCpuenKzXbaFMggGbnUIdvvzkV_S1l_Vzg2NYt1N03_Dsvg5O68WlIyhrxsKVnAorafeF9O6tSkQELVuckD9G9-P_7V-JfUYLaOuYsl82WVx607vlu1IOqfkjM7LndOfUnmu9coVFU68bum3CN90vvLHsww6QUwQMfhz5l-_UkDToB-nsf6QFSrol1GePOLZe_KGLDjZ0wSrWkv1FjFo7-_UbiIy0V3ywPLl2s2CGstc6O3IL4dTLIS2DSpaUDScBynkWNs4RdoxvEXwLpHKTgcJnTbZBulhbpqAVT8ZgxeBDEcmOhDfN5JJClRHgvm6fju8EWBEaG8X6Q6ymIXnXx4mU0rUDrfXLytDi8iB6FcG6NwRg_ASg9LM0q5i4LUCDXuhUKgZsuF-MjF3olFAkw-X-yqM4FiCAHsEmJGDC9jFID9-Cy8BGkyAgbqaAMu-3iC-UJ0WxfR58IHe4aBsbHpG9_mB9NpmBkptXzHgYo7-_upFVuEOU80mo17QeysaDfRdLPM-cLY42w-B6WO_mftA6bbTf5-xXVkxl7Ls2Tcjqmv5Ct4q3msRqncDfhrE7axLvl4-uesxAMUbzYKaUgscddq2-FzenclP99bqRSgbXru67-1uPYjtHeRPRVl076s-kabN-AyHuYTBOsfccxnTuMgXw6hBVEIcohXCuLEda5bYcR0Q-P8BQbzlnPMmouFb6i6ln-H8uk32y-gyyZhLr-N8V5uo2cQ6st8R2JGP_um4Ewj8BRhBUSktJNnHOLW0ORJyhP8JawlC9EBDJVNpx-DYYrFd5zgMcKX0-J1ROuwXiYTv4qkpmIDvWz0M3EXQkJv57uxyov3aze5azm5q5IsT0E2aUvOxSBVgqNXuv3HN4C2_7zuPDWlK9C8J-CQBD3-u0ZTbh8yErmXr7HERtRevVycl2Z8p9VhUMIFX2ytyQjJMi46wZY2Tm1ZPXzDVorp1efqfmdGSmI-KnM3e6MdPP4BYf8EvqBaD91LqxpFTCxhfwBLtinvgVBTsZJuYO9H8pIhQHJ-2O_rmVgky7D6stYi7nytx0SyG8bej4XdiJEmq4doezedVbT-9LeMoyQGjpEs_1uTsngWnKJF9mWvyYIejF-8Prja_xndCRCkMHvNX87GLTAeCGLJJbwqBX-YIxABiqb2IGsdZ0HzAZl-3LO8qi8b4Y942rvgw5F3yoZI6ql1RAFeMOkHU56otHtKj1JfEATxU2Td33hfVBCyBbg_HQ4dAJ5lyiptF1qT9-n4GS-iaJqtPHhmhW56NSyck2K7_xne4GeoH0fuG5o5CZAJMaNMJwsVLi7jHCl55NjADhB5VQP7jGWTYcUSDKljhTsbGJphhbog1p3XhwWthRMmi7gNoPcKGJTTUHggOPhM5XfsC7pc5V-Tl2gZSZwZtrCxXSebXoRIfC-3flyceTfhUnR0vyu8cmIHC18Yg1PU2sC77I4Car44oG1VIAnLkf9FafMFW46DmswLC-rkm86CO8gC6yiaHRU6xBB7CEZsa6FsdcNzat92HUOSlj5QwPPzjRsdIx__6jnp65agtIsCUXPzSOexmlV51pc0_zUR0i83h-ijQV_ILFHjx7CBPxm8QEQJSy45e_sDIBMOn4EjkCtvRBdA2U3PA_oTcVwgOirRw5glHSQVl6cxnbXSf5e1Sn3O15WgiBqp9WtpkvOG6JEt1moa8Eh2jz-VRBa5gtUe2RSEbZZPQEfY-9hYhhqZegtC1d3MPcoHCarAnjWJvOYQsKtwiSm22oz2lprjUSG6Q4SDG8JxMoOZx5hYKiwOTA7fKx79Apg9xVuurKadxUat8rgQtX48GQsY-8FPIgizR3wqt9XnCBaZSwIevJ81e2RO2da-I1EXYnfN7x8xUeuRhbZjAivxk4dxigOUSEa5uBCaDNWoCSoUohbwndB-lk1_AB1ApPPuuS7Yvd2qkwEGowI-GlrtJ7K2cEVGvArzN7QabNOGuJuVTII98JI_QoPbC_AbwvTC4g2sOCf4FU61iBVK8tT96QkLRAAUX88ufsou9R_hQ5uKD1wCwnSZr6pPemBtnV_y4tobwnXLIdsF44Bkju6zNdGOtm7EG_dEKvJpp8v3nc5D3mypAmfpIkECot8AHJ9ShjAEO9I3O3GJzDz6ErVSBSKzmiRz6wYzNUl6p_yylVyAEGvNPw73DYM86xrvBEr3HQ11fx3p8uBC-UXpu7c0X0RGHtOSvnr7GA-P_hfTU4Weav0RI1nPflI-rGO8ORX0qqxzbrDzct0t-WO5u3jZlxZb66mwv2wgPzJWFZ8WPdr-9OyYmuJi18_jtFZvXIHW-77SGCj3-prsm5T3gyQ0D88uar27ho-mKOwEWP7roNtiA1BgTY8p-G8Eu_c86C_-ajma27Ht5tsjsoiOZTSSGBKnamSgeYKchDj8SBOr-TaQg1-Op-3tmWoz3eWqE7v-IgdcRJXmoV7g2SmdwRn-UdRM-NUO09YzjHGN5VE6UsIAXXhgg8rjQ0ciTBl3m04yA.0a7LtfM-FcB6rQ1AxG3How" # 刷新cookie,目前版本不再推荐使用,建议直接从getsession接口写入账号信息 默认值 ""
# OAUTH_URL: https://xxxxx.xxx.com/ouath # oauth地址 用于集成第三方登录 默认值 ""
# LOGIN_CALLBACK: "/login" # 登录回调地址,用于指定自己的登录页面 默认值 "/login"
# ASSET_PREFIX: https://oaistatic-cdn.closeai.biz # 静态资源前缀,用于指定自己的静态资源地址 默认值 https://oaistatic-cdn.closeai.biz
# ARKOSE_URL: https://tcr9i.closeai.biz/v2/ # arkose地址,用于指定自己的arkose人机验证地址 默认值 https://tcr9i.closeai.biz/v2/
ADMIN_PASSWORD: ycyawCOM996. # 管理员密码 默认值为随机字符串,每次启动都会变化，可以在启动时通过日志查看，也可以指定一个固定值，方便管理
# AUDIT_LIMIT_URL: https://auditlimit.closeai.biz/audit_limit # 审计限制url 默认值 ""

# 以下配置不兼容环境变量设置,只能通过配置文件设置
USERTOKENS: # 用户token,可配置多个,本项内容支持热更新,更改后即时生效
  - "tanqi-001"
  - "heyuanjun-001"
  - "faohdsf-fakdjf"
  - "yss-990"
# PROXY: "http://127.0.0.1:31280"  # 代理地址
# OAUTH_URL: https://xxxxx.xxx.com/ouath

# 注意注意,以下为新增配置,如需自动创建数据库,必加以下配置
cool:
  autoMigrate: true


# sqlite数据库配置
database:
  default:
    type: "sqlite" # 数据库类型
    name: "./config/cool.sqlite" # 数据库名称,对于sqlite来说就是数据库文件名
    extra: busy_timeout=5000 # 扩展参数 如 busy_timeout=5000&journal_mode=ALL
    createdAt: "create_time" # 创建时间字段名称
    updatedAt: "update_time" # 更新时间字段名称
    # debug: true # 开启调试模式,启用后将在控制台打印相关sql语句

# mysql数据库配置

# database:
#   default: # 数据源名称,当不指定数据源时 default 为默认数据源
#     type: "mysql" # 数据库类型
#     host: "127.0.0.1" # 数据库地址
#     port: "3306" # 数据库端口
#     user: "root" # 数据库用户名
#     pass: "xxxxxxxxx" # 数据库密码
#     name: "cockroachai" # 数据库名称
#     charset: "utf8mb4" # 数据库编码
#     timezone: "Asia/Shanghai" # 数据库时区
#     # debug: true # 是否开启调试模式，开启后会打印SQL日志
#     createdAt: "createTime" # 创建时间字段
#     updatedAt: "updateTime" # 更新时间字段
